### ISSUE TITLE
[Bug]: cant render tree on form

### ISSUE THREAD

**Issue by nilsir** [CodeWithDennis/filament-select-tree#102]
### What happened?

<img width="662" alt="image" src="https://github.com/CodeWithDennis/filament-select-tree/assets/15967737/641cf33c-5638-44d1-9d70-cb65fc6509b6">

### How to reproduce the bug

<img width="656" alt="image" src="https://github.com/CodeWithDennis/filament-select-tree/assets/15967737/8d196421-94b4-42d4-9a63-37077cd1684f">

<img width="756" alt="image" src="https://github.com/CodeWithDennis/filament-select-tree/assets/15967737/0c075d01-b535-4a3c-8092-1f9d9736664c">

### Package Version

3.1.39

### PHP Version

8.3.2

### Laravel Version

10.48.7

### Which operating systems does with happen with?

macOS

### Notes

<img width="696" alt="image" src="https://github.com/CodeWithDennis/filament-select-tree/assets/15967737/4c405891-cdeb-46ff-984d-853060c6e2de">

**Comment by CodeWithDennis** [comment]
If pid refers to the parent it belongs to, you should likely utilize `->parentNullValue(0)`.

**Comment by nilsir** [comment]
Thank you for your help, it's work ok.
