### ISSUE TITLE
[Bug]: more than one SelectTree in form 

### ISSUE THREAD

**Issue by MiranSalehi** [CodeWithDennis/filament-select-tree#107]
### What happened?

<img width="949" alt="Screenshot 1403-01-31 at 12 55 18 PM" src="https://github.com/CodeWithDennis/filament-select-tree/assets/50701268/fb7821f1-67ac-467d-b4d7-46c6c8d24876">

**In this case, only the last SelectTree save on create and edit page**

### How to reproduce the bug

I have two types of category and need two SelectTrees

### Package Version

3.1

### PHP Version

8.3.4

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by CodeWithDennis** [comment]
Interesting, could you try and add `->id('someKey')` (different key names)
Curious if that works.

**Comment by MiranSalehi** [comment]
> Interesting, could you try and add `->id('someKey')` (different key names) Curious if that works.


yes, I have tried it, but it still doesn't work. @CodeWithDennis

**Comment by CodeWithDennis** [comment]
> > Interesting, could you try and add `->id('someKey')` (different key names) Curious if that works.
> 
> 
> 
> 
> 
> yes, I have tried it, but it still doesn't work. @CodeWithDennis 

I will do some more digging when i can

**Comment by MiranSalehi** [comment]
> > > Interesting, could you try and add `->id('someKey')` (different key names) Curious if that works.
> > 
> > 
> > yes, I have tried it, but it still doesn't work. @CodeWithDennis
> 
> I will do some more digging when i can


thanks

**Comment by CodeWithDennis** [comment]
@MiranSalehi Sorry for the delayed response, but I couldn't reproduce the issue.

https://github.com/CodeWithDennis/filament-select-tree/assets/23448484/59e28650-a441-4df0-82e9-c8ed1b491009

**Comment by MiranSalehi** [comment]
> @MiranSalehi Sorry for the delayed response, but I couldn't reproduce the issue.
> 
>  Schermopname.2024-05-30.om.10.09.12.mov

Thank you for following up on this issue, I must have made a mistake somewhere

**Comment by CodeWithDennis** [comment]
Let me me know if you can find the problem.

**Comment by MiranSalehi** [comment]
> Let me me know if you can find the problem.

sure
