### ISSUE TITLE
[Bug]: loaded https://code.jquery.com/jquery-3.6.0.min.js in FilamentTreeServiceProvider

### ISSUE THREAD

**Issue by MiranSalehi** [CodeWithDennis/filament-select-tree#109]
### What happened?

https://code.jquery.com/jquery-3.6.0.min.js  is loaded from external link , 
thats make panel so slow

### How to reproduce the bug

<img width="1249" alt="Screenshot 1403-02-10 at 10 10 59 PM" src="https://github.com/CodeWithDennis/filament-select-tree/assets/50701268/b95a7c62-9d4f-458f-aad6-25c7ed39f09f">

### Package Version

3.1

### PHP Version

8.3.4

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by CodeWithDennis** [comment]
What? This code is not part of the package 🤔

**Comment by MiranSalehi** [comment]
> What? This code is not part of the package 🤔

Sorry that was my mistake, the name was similar to another package 🙏
