### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dani7115** [CodeWithDennis/filament-select-tree#110]
### What happened?

I have installed the repository and tried to use like this 

  SelectTree::make('categories')
                            ->relationship('categories', 'title', 'parent_id')
                            ->columnSpanFull(),
                            
                            But i am facing this error 
                            
![CleanShot 2024-05-02 at 10  38 38@2x](https://github.com/CodeWithDennis/filament-select-tree/assets/20567120/8246806e-916c-493e-bc1b-d8dbcd2795c1)

                            
                            Trait "Filament\Forms\Components\Concerns\HasPivotData" not found

### How to reproduce the bug

Install and try to use SELECT TREE AS

  SelectTree::make('categories')
                            ->relationship('categories', 'title', 'parent_id')
                            ->columnSpanFull(),

### Package Version

2.0.0

### PHP Version

8.2.0

### Laravel Version

10.48

**Comment by CodeWithDennis** [comment]
Please update Filament to the latest version
