### ISSUE TITLE
[Bug]: Triat Not anymore in Filament 

### ISSUE THREAD

**Issue by codeies** [CodeWithDennis/filament-select-tree#112]
### What happened?

The triat \Concerns\HasPivotData; is no longer there availible in Filament Checkout the link

https://github.com/filamentphp/filament/tree/3.x/packages/forms/src/Concerns

### How to reproduce the bug

Triat Not Found

### Package Version

3.1.40

### PHP Version

8.2

### Laravel Version

10.0

**Comment by CodeWithDennis** [comment]
https://github.com/filamentphp/filament/blob/3.x/packages/forms/src/Components/Concerns/HasPivotData.php
