### ISSUE TITLE
[Bug]: Overflow Issue: Selected Options is Overflowing Outside of the Element

### ISSUE THREAD

**Issue by RuddraNickBiswas** [CodeWithDennis/filament-select-tree#115]
### What happened?

**Modal**
![Screenshot_20240617_143136](https://github.com/CodeWithDennis/filament-select-tree/assets/63276603/0f17f9dd-7c5d-4166-8788-aa1ea7eb42df)

**Responsive Mode**
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/63276603/e5fafd31-476a-451a-bb4e-92ff4f7691b7)

I've encountered an issue where the selected category in my application is overflowing outside of its designated element when the category name is too long. 

some kind of auto text truncate functionality would be great in here!

### How to reproduce the bug

This issue occurs consistently when selecting categories with longer names.

### Package Version

3.1

### PHP Version

8.2

### Laravel Version

11.9

**Comment by CodeWithDennis** [comment]
I can' seem to reproduce this issue, perhaps you can make a reproduction repo?

![Scherm­afbeelding 2024-06-25 om 10 42 12](https://github.com/CodeWithDennis/filament-select-tree/assets/23448484/6ac8a9b7-745a-431b-b092-21f3d4579009)

**Comment by CodeWithDennis** [comment]
@RuddraNickBiswas

**Comment by RuddraNickBiswas** [comment]
@CodeWithDennis 
sir! Problem is fixed I just checked with my project! maybe It was with filament core select Input! Last time I checked It had same problem with filament core select component!! I thought I put comment In here about that but I forgot! Sorry!!
