### ISSUE TITLE
[Bug]: in belongsToMany i have problem , doesn't show  groups

### ISSUE THREAD

**Issue by wisedev99** [CodeWithDennis/filament-select-tree#120]
### What happened?

Validation: you should pass an array as a value!      !i && !Array.isArray(n) && console.error("Validation: you should pass an array as a value!"),

![Screenshot 2024-08-14 at 12 04 35](https://github.com/user-attachments/assets/b2b7ecf0-78e9-4437-9234-0768f5fd71df)

![Screenshot 2024-08-14 at 13 07 29](https://github.com/user-attachments/assets/6ae7a7b0-9915-4215-b682-f1a17eee759b)

### How to reproduce the bug

     SelectTree::make('groups')
              ->relationship('groups', 'name',  'parent_id')

<img width="905" alt="Screenshot 2024-08-14 at 12 02 14" src="https://github.com/user-attachments/assets/e1832242-9885-443d-a464-0dc89a3aec6f">

   in course model   public function groups(): BelongsToMany
    {
        return $this->belongsToMany(Group::class);
    }
in group model   public function courses(): BelongsToMany
    {
        return $this->belongsToMany(Course::class);
    }

### Package Version

3.1

### PHP Version

8.3

### Laravel Version

11

**Comment by CodeWithDennis** [comment]
Since you closed it, i assume you figured it out? @wisedev99

**Comment by DevYSM** [comment]
I have the same issue 

Validation: you should pass an array as a value!

**Comment by dharen008** [comment]
Anyone solve this? i got the same issue. anyone help please? @CodeWithDennis 

SelectTree::make( 'teams' )
->relationship( 'teams', 'name', 'department_id' )

Model with belongsToMany Pivot model TeamUser
public function teams()
	{
		return $this->belongsToMany( Team::class )
			->using( TeamUser::class );
	}
	
Database Table team_user structure
![image](https://github.com/user-attachments/assets/b00197be-7004-4e07-87df-818c1ded46f3)

**Comment by mpskovvang** [comment]
I had the same issue. I solved it by passing an empty array to the default state:

```
SelectTree::make('categories')->default([])
```

I'm using the component in a create-only resource.

**Comment by dharen008** [comment]
> I had the same issue. I solved it by passing an empty array to the default state:
> 
> ```
> SelectTree::make('categories')->default([])
> ```
> 
> I'm using the component in a create-only resource.

@mpskovvang tried it and got error "Typed property CodeWithDennis\FilamentSelectTree\SelectTree::$relationship must not be accessed before initialization"

SelectTree::make( 'departments')->default([])

in my model:
public function departments()
	{
		return $this->belongsToMany( Department::class )
			->using( DepartmentUser::class );
	}
