### ISSUE TITLE
[Bug]: Performance issue with opening categories (large dataset with nested children)

### ISSUE THREAD

**Issue by dhruva81** [CodeWithDennis/filament-select-tree#122]
### What happened?

In my application, I have over 5000 categories, (up to 4 levels of nested children). Due to the large number of categories and the deep nesting, the interface becomes very slow when trying to open the categories, and sometimes it freezes altogether.

Is there any way to optimize the performance for handling such a large dataset?

### How to reproduce the bug

Have over 5000 categories in the application, structured with multiple levels of nested children.
Attempt to open the categories section in the application.

### Package Version

3.1.42

### PHP Version

8.2.0

### Laravel Version

11

**Comment by CodeWithDennis** [comment]
Thanks for reporting this issue. It's a known problem because the plugin loads all the records when building the tree. Unfortunately, the underlying package doesn't have a feature to load on collapse.
