### ISSUE TITLE
[Bug]: The input is not fully visible

### ISSUE THREAD

**Issue by jadersbr** [CodeWithDennis/filament-select-tree#124]
### What happened?

I don't know why, but in my application, the SelectTree is not fully visible, sometimes it is, and other times it's not. When this happens, if I refresh the screen in any way, like clicking the toggle that changes the status, then the input opens fully.

### How to reproduce the bug

To reproduce, just install the plugin and configure it as follows:

```
SelectTree::make('parent_id')
    ->label('Categoria pai')
    ->placeholder('Selecione uma categoria')
    ->enableBranchNode()
    ->relationship(
        relationship: 'parent',
        titleAttribute: 'title',
        parentAttribute: 'parent_id',
        modifyQueryUsing: fn (Builder $query) => $query
            ->where(column: 'status', operator: '=', value: BaseStatus::ACTIVE),
    )
    ->searchable()
    ->columnSpan(6),
```
                                  	

### Package Version

3.1

### PHP Version

8.2

### Laravel Version

11.21

### Which operating systems does with happen with?

Windows

### Notes

Could you help me fix this issue? See my video:

https://github.com/user-attachments/assets/c05744e7-82e3-4b5b-8ac7-f74de568e01c

**Comment by CodeWithDennis** [comment]
Could you try to make a reproduction repository?

**Comment by gabyyro** [comment]
@jadersbr Did you find a solution for this?

**Comment by CodeWithDennis** [comment]
I think its similar to https://github.com/CodeWithDennis/filament-select-tree/issues/141 and not sure what is causing it.

**Comment by gabyyro** [comment]
@CodeWithDennis I think is related to spa mode. Does not seem to be an issue if spa is disabled.

**Comment by ineffablesam** [comment]
[Check this Comment](https://github.com/CodeWithDennis/filament-select-tree/issues/141#issuecomment-2726300911)
That's just a workaround for the time being i have disabled the spa mode for specific page which uses the SelectTree component.
