### ISSUE TITLE
[Bug]: Select input zoom in on mobile

### ISSUE THREAD

**Issue by markvaneijk** [CodeWithDennis/filament-select-tree#125]
### What happened?

The select zooms in on mobile when you want to select or search.

### How to reproduce the bug

Using a mobile device.

### Package Version

3.x

### PHP Version

8.3

### Laravel Version

11.x

### Which operating systems does with happen with?

macOS

### Notes

The fix is making sure font-size is 16px on mobile devices.

**Comment by CodeWithDennis** [comment]
Hi Mark, I can't seem to reproduce the issue. Could you send me a video showing what's happening?

**Comment by markvaneijk** [comment]
Yes, here it is: 

Uploading ScreenRecording_10-27-2024 17-24-44_1.mp4…

**Comment by markvaneijk** [comment]
Yes, here it is: 

https://github.com/user-attachments/assets/8074d346-0381-4558-9ef7-e4a40ce1cebe

**Comment by markvaneijk** [comment]
This is typical iOS behaviour and is fixed by setting the font-size to 16px (just like Filament does for normal inputs etc.)

**Comment by CodeWithDennis** [comment]
That's some interesting behavior! I can add `.sm\:text-sm` to the field, like a Filament field. I’ll create a PR tomorrow, and you can check it to see if it fixes your problem. Alternatively, you can also submit a PR.

**Comment by CodeWithDennis** [comment]
Hi @markvaneijk, I still can’t seem to see the issue on my end. I tested it on my iPhone 15 Pro Max and on my MacBook Pro in phone mode, but it’s not happening for me. I’m sorry, but I can’t fix a problem I can’t recreate 😅. 

Could you try making a fix with before-and-after examples? That way, we can still solve the problem for you and i can put it in the next release.

**Comment by markvaneijk** [comment]
> Hi @markvaneijk, I still can’t seem to see the issue on my end. I tested it on my iPhone 15 Pro Max and on my MacBook Pro in phone mode, but it’s not happening for me. I’m sorry, but I can’t fix a problem I can’t recreate 😅.
> 
> Could you try making a fix with before-and-after examples? That way, we can still solve the problem for you and i can put it in the next release.

Fixed it in #127 with video as proof 😄
