### ISSUE TITLE
How to use afterStateUpdated?

### ISSUE THREAD

**Issue by cmayorgahilario** [CodeWithDennis/filament-select-tree#31]
How to use afterStateUpdated in SelectTree? 

in Select

```php
->afterStateUpdated(fn (string $operation, Forms\Components\Select $component, Forms\Set $set) => 'create' === $operation ? $set('name_alias', $component->getOptionLabel()) : null)
```

but this method "getOptionLabel" no exist in SelectTree

**Comment by CodeWithDennis** [comment]
The `SelectTree` is not a select field so you cant really do this.

**Comment by cmayorgahilario** [comment]
How could I obtain the "name" of the selected option or options?

**Comment by CodeWithDennis** [comment]
Right now, it's not officially supported, but you could try something like this:

```php
->afterStateUpdated(function (string $operation, SelectTree $component, $state) {
   // If it's a single select: Category::find($state);
   // For multi-select: Category::whereIn('id', $state)->get();
}),
```

I'll check if we can make this officially supported down the road
