### ISSUE TITLE
[Bug]: Can not select a sub tree element

### ISSUE THREAD

**Issue by Hegabovic** [CodeWithDennis/filament-select-tree#35]
### What happened?

i have a tree which consists of for example roles : 
-team leads 
   - seniors 
      - juniors

i want the select to show the hierarchy and be able to locate the users inside each level 

 
     
![Screenshot](https://github.com/CodeWithDennis/filament-select-tree/assets/56083879/b81b137d-6a6d-4fbd-aa78-1604efb112e4)

each level should be allowed to be selected

### How to reproduce the bug

create hierarchy and try to choose the second option or any one in the middle , you can't 

### Package Version

3.1.6

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

Linux

**Comment by CodeWithDennis** [comment]
Have you looked at `->enableBranchNode()`?

**Comment by Hegabovic** [comment]
yes , and it didn't work

**Comment by Hegabovic** [comment]
when i reinstalled the package and try it with all the defaults it worked just fine

**Comment by CodeWithDennis** [comment]
```php
SelectTree::make('categories')
   ->relationship('categories', 'name', 'parent_id')
   ->independent(false)
   ->enableBranchNode(),
```

https://github.com/CodeWithDennis/filament-select-tree/assets/23448484/b9f4a36f-ff81-4e8f-85b1-7086a5c77fed
