### ISSUE TITLE
Using it with massive amount of data

### ISSUE THREAD

**Issue by wouldhide** [CodeWithDennis/filament-select-tree#36]
Hi, i really like this component, but i'm trying to use it with a massive set of data, which makes it really slow.
Is it possible to add an option to only load the first level on startup and make a separate query to load the children once a node is expanded?
I can see that you query the full set of data in the buildTree method and build the tree there but in my case this creates a huge js object and slows down everything.
Thanks!

**Comment by CodeWithDennis** [comment]
I'm aware of this problem, but unfortunately, I haven't come across a viable solution yet because this package is dependent on another one.

**Edit:** Perhaps you could narrow down the results with a custom query, but I'm not certain if that will be effective in your situation.

**Comment by wouldhide** [comment]
Thanks for the reply! I extended the plugin and tried to fiddle around to only partially load the data, but i wasn't very successful. Thanks anyway, i'll close this issue.

**Comment by CodeWithDennis** [comment]
> Thanks for the reply! I extended the plugin and tried to fiddle around to only partially load the data, but i wasn't very successful. Thanks anyway, i'll close this issue.

If you do find a good way feel free to PR!
