### ISSUE TITLE
[Feature Request]: Hide specific option from the tree

### ISSUE THREAD

**Issue by ivanBell199** [CodeWithDennis/filament-select-tree#40]
Thank you for this package, it's great! I wanted to use it in my "Category" form to select the parent category. It's working very well, but I have one issue. When editing a category, it is included in the select tree. Of course, a category cannot be parent to itself. Is it possible to hide it from the tree or make it unclickable? Or maybe you would consider adding this feature to the package. Thanks again.

**Comment by CodeWithDennis** [comment]
I'm happy you like the package! To fix the problem you mentioned, you can try using `->enableBranchNode(false)` or simply remove the method from the tree.

```php
SelectTree::make('categories')
   ->relationship('categories', 'name', 'parent_id')
   ->enableBranchNode(false),
```

<img width="683" alt="Scherm­afbeelding 2023-11-15 om 22 12 25" src="https://github.com/CodeWithDennis/filament-select-tree/assets/23448484/54d0dc1a-3dfc-48a1-8752-98669aa05c8f">

**Comment by ivanBell199** [comment]
Thanks for such a quick reply! It seems I wasn't clear enough in my explanation. I have CategoryResource in my Filament project. Let's say I create category "Electronics" and then inside it "PCs". Then I go to the Edit page for "PCs". There I have the tree of categories in case I need to reassign parent. As you can see, "PCs" is present in this tree:
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/65890952/c75cef5a-2e6a-43c2-836e-3f3ffdad1aad)
Of course, it should be obvious that you can't set "PCs" as parent for itself. But for the sake of better UX I think it would be good to disable this option or remove from the tree. Unfortunately, I don't have enough coding skill to achieve that. So if you can give me a hint how to solve my problem, I will be very grateful :)

**Comment by CodeWithDennis** [comment]
This is not currently supported. However, I'll check the possibility of implementing something similar to the following:

```
->hideOptions([3,5,7])
```

```
->disableOptions([3,5,7])
```

**Comment by ivanBell199** [comment]
Sounds great, thank you!

**Comment by CodeWithDennis** [comment]
> Sounds great, thank you!

I just dropped version v3.1.9, and now you can disable options.

<img width="440" alt="example-disable-options" src="https://github.com/CodeWithDennis/filament-select-tree/assets/23448484/f2c8e822-eb9a-4a17-9df8-dbf6fd183b8a">

**Comment by ivanBell199** [comment]
Works nicely! Thank you for your work!

**Comment by buzkall** [comment]
I've done PR https://github.com/CodeWithDennis/filament-select-tree/pull/55 to add the code to hide options
```
->hideOptions([id])
```
