### ISSUE TITLE
[Suggestion]: Add an example of filter for BelongsTo relationship

### ISSUE THREAD

**Issue by ivanBell199** [CodeWithDennis/filament-select-tree#42]
I have just added SelectTree to my ProductResource table as a filter. Every product belongs to one category. I think it is a pretty typical situation, so it could be of help to have a sample code in the documentation. If you find this idea relevant, here is my code that works well in my project:

```
->filters([
    Filter::make('tree')
        ->form([
            SelectTree::make('category_id')
                ->relationship('category', 'name', 'parent_id'),
        ])
        ->query(function (Builder $query, array $data): Builder
        {
            return $query->when(
                $data['category_id'],
                fn ($query, $category_id) => $query->whereRelation('category', 'id', $category_id)
            );
        })
        ->indicateUsing(function (array $data): ?string
        {
            if (!$data['category_id']) return null;
            return __('Category') . ': ' . Category::find($data['category_id'])->name;
        })
])
```

**Comment by CodeWithDennis** [comment]
I've already provided a straightforward example, and I believe introducing another one is unnecessary, especially considering it's more of a filament-related matter.

**Comment by ivanBell199** [comment]
I agree. Thanks for considering my idea :)
