### ISSUE TITLE
[Bug]: Associated data cannot be viewed if they are disabled options

### ISSUE THREAD

**Issue by omarabdelaz1z** [CodeWithDennis/filament-select-tree#50]
### Scenario
When editing the user that shares the disabled options.

### Code Snippet
```php
Forms\Components\Section::make('Store Info')->schema([
    Forms\Components\Select::make('store_code')
        ->options(Store::query()->pluck('name', 'code'))
        ->preload()
        ->live()
        ->required()
        ->native(false)
        ->placeholder('Select Store')
        ->afterStateUpdated(function (Set $set, Get $get, ?Model $record) {
            $storeCode = $get('store_code');

            if ($storeCode === null) {
                return $set('categories', null);
            }

            if ($record === null || $record->store_code !== $storeCode) {
                return $set('categories', null);
            }

            return $set('categories', $record->categories()->pluck('category_id'));
        }),
    SelectTree::make('categories')
        ->relationship('categories', 'name', 'parent_id')
        ->withCount()
        ->independent(false)
        ->enableBranchNode()
        ->searchable()->noSearchResultsMessage('No categories found')
        ->placeholder(
            fn(Get $get): string => !$get(
                'store_code'
            ) ? 'Select Store First..' : 'Select Categories..'
        )
        ->disabled(function (Get $get, Set $set): bool {
            if ($get('store_code') === null) {
                $set('categories', null);

                return true;
            }

            return false;
        })
        ->disabledOptions(function (Get $get): array {
            return Category::query()->whereHas(
                'users',
                fn($query) => $query->where('store_code', $get('store_code'))
            )->pluck('id')->toArray();
        }),
])->columns(),
```
### Expected
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/59033999/951087de-9af4-49c9-b8d0-94b497b71f9e)

### Actual
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/59033999/8473d9aa-3a2f-4667-89b4-666b98254e62)

### How to reproduce the bug

1. Create a user and attach categories to the user.
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/59033999/152c2e04-633d-4320-957b-123b44fdd6bd)

2. Try to edit the created user, the options on the same store are disabled and not shown
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/59033999/a404caea-0261-4d15-aa4a-e66fe7c5bc9f)

### Package Version

3.1.13

### PHP Version

8.1

### Laravel Version

10.10

### Which operating systems does with happen with?

Linux

**Comment by CodeWithDennis** [comment]
I believe this isn't a bug; when options are disabled, they cannot be selected. Therefore, you may need to modify your query. If your tree has independent nodes, you can still choose sub-items.

<img width="668" alt="Scherm­afbeelding 2023-11-27 om 09 37 44" src="https://github.com/CodeWithDennis/filament-select-tree/assets/23448484/e215db5b-2f66-45c0-bfe0-55244eebe796">

**Comment by omarabdelaz1z** [comment]
Do you mean the query inside `disabledOptions` method?

**Comment by CodeWithDennis** [comment]
> Do you mean the query inside `disabledOptions` method?

Yes

**Comment by omarabdelaz1z** [comment]
Yes, you are right. It is solved now.
I thought it was a bug.
