### ISSUE TITLE
[Feature]: createOptionForm

### ISSUE THREAD

**Issue by aeq-dev** [CodeWithDennis/filament-select-tree#53]
### What happened?

Is it possible to add this option

### How to reproduce the bug

Just same as Select input

### Package Version

3.1.14

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

Linux

**Comment by CodeWithDennis** [comment]
Perhaps in the future, but if you really need it quickly you can make a PR.

**Comment by CodeWithDennis** [comment]
This is now supported in [v3.1.19](https://github.com/CodeWithDennis/filament-select-tree/releases/tag/v3.1.19). @aeq-dev

**Comment by aeq-dev** [comment]
Thanks dear @CodeWithDennis :)
