### ISSUE TITLE
[Bug]: Column not found: 1054 Unknown column 'field' in 'field list' 

### ISSUE THREAD

**Issue by aeq-dev** [CodeWithDennis/filament-select-tree#54]
### What happened?

I have product model BelongsToMany collections model,
Here's my code :
 **ProductResource**
```
SelectTree::make('collections')
    ->label(__('Collections'))
    ->emptyLabel(__('No results found'))
    ->relationship('collections', 'name', 'parent_id', function ($query) {
        return $query->whereLocale('name', app()->getLocale());
    })
    ->searchable()
    ->withCount(),
```
After saving the product record, it saves the relationship ids in product_collection, but an error appears : 
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'collections' in 'field list'

update
  `products`
set
  `has_variants` = 0,
  `collections` = [ 1,
  2,
  3 ],
  `products`.`updated_at` = 2023 -12 -06 15: 44: 09
where
  `id` = 1
```

### How to reproduce the bug

1. Setup BelongsToMany relationship
2. Setup SelectTree as mentioned in the doc
3. Create / update record on adding relationship ids
4. Save

### Package Version

3.1.14

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

Linux

**Comment by CodeWithDennis** [comment]
Can you try to rename your relationship to something else and try again, i´m wondering if its because of the name.

**Comment by CodeWithDennis** [comment]
Can you also show your Product model?

**Comment by aeq-dev** [comment]
```
public function collections(): BelongsToMany {
    return $this->belongsToMany(Collection::class, 'product_collections')->withTimestamps();
}
```

**Comment by aeq-dev** [comment]
> Can you try to rename your relationship to something else and try again, i´m wondering if its because of the name.

It works fine if I use Select Filament component

**Comment by CodeWithDennis** [comment]
Im not sure what is going wrong on your side, this is what my resource looks like:

```php
public static function form(Form $form): Form
{
    return $form
        ->schema([
            Forms\Components\TextInput::make('name')
                ->required()
                ->live()
                ->maxLength(255),

            SelectTree::make('categories')
                ->label(__('Category'))
                ->relationship('categories', 'name', 'parent_id')
                ->enableBranchNode(),
        ]);
}
```

Blog.php

```php
public function categories(): belongsToMany
{
   return $this->belongsToMany(Category::class);
}
```


Migrations

```php

public function up(): void
    {
        Schema::create('categories', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->foreign('parent_id')->references('id')->on('categories');
            $table->timestamps();
        });
    }
    
```

```php
public function up(): void
    {
        Schema::create('blog_category', function (Blueprint $table) {
            $table->unsignedBigInteger('blog_id')->nullable();
            $table->foreign('blog_id')->references('id')->on('blogs')->cascadeOnDelete();
            $table->unsignedBigInteger('category_id')->nullable();
            $table->foreign('category_id')->references('id')->on('categories')->cascadeOnDelete();
        });
    }
```

**Comment by aeq-dev** [comment]
In EditRecord of Filament resource, 
 ```
protected function validateFormAndUpdateRecordAndCallHooks(): void
    {
        $this->callHook('beforeValidate');

        $data = $this->form->getState();

        $this->callHook('afterValidate');

        $data = $this->mutateFormDataBeforeSave($data);

        $this->callHook('beforeSave');

        $this->handleRecordUpdate($this->getRecord(), $data);

        $this->callHook('afterSave');
    }
```
if I use select filament, and do **dd($data)** after        ` $data = $this->mutateFormDataBeforeSave($data);` I wont' find collections field, but when using your component, I find it, so after that,         `$this->handleRecordUpdate($this->getRecord(), $data);` will occur the error !

**Comment by aeq-dev** [comment]
NB: Also, it works fine with belongsTo relationship,

**Comment by CodeWithDennis** [comment]
There must be some configuration issues with your relationships.

**Comment by abrardev99** [comment]
Facing same issue. 

Defined like this: 
```
SelectTree::make('siteCategories')
 ->relationship('siteCategories', 'name', 'parent_id'),
```

Instead of saving to relationship, it trying saving to model itself. 

<img width="1224" alt="image" src="https://github.com/CodeWithDennis/filament-select-tree/assets/54532330/3e66004b-11dc-4aba-bc89-c3bb2393aa45">

**Comment by CodeWithDennis** [comment]
Can you share your models / migrations? @abrardev99

**Comment by abrardev99** [comment]
here is code, not whol but relevant. 

 Accommodation.php 
```
class Accommodation extends Model 
{
    public function siteCategories(): BelongsToMany
    {
        return $this->belongsToMany(SiteCategory::class);
    }
}
```

SiteCategory.php
```
class SiteCategory extends Model
{
    protected $guarded = [];

    protected $table = 'site_categories';

    public function accommodations(): BelongsToMany
    {
        return $this->belongsToMany(Accommodation::class);
    }
}
```

## migrations

accommodations table
```
Schema::create('accommodations', function (Blueprint $table) {
            $table->bigIncrements('id');
}
```

site_categories table
```
Schema::create('site_categories', function (Blueprint $table) {
    $table->bigIncrements('id');
}
```

pivot table
```
Schema::table('accommodation_site_category', function (Blueprint $table) {
            $table
                ->foreign('site_category_id')
                ->references('id')
                ->on('site_categories')
                ->onUpdate('CASCADE')
                ->onDelete('CASCADE');

            $table
                ->foreign('accommodation_id')
                ->references('id')
                ->on('accommodations')
                ->onUpdate('CASCADE')
                ->onDelete('CASCADE');
        });
```

I can set up a reproduction repo if you want?

**Comment by abrardev99** [comment]
@CodeWithDennis I noticed it saved the relationship, and the exception happened after it. Looks like after saving the relationship, it fills Accommodation model properties

**Comment by CodeWithDennis** [comment]
@abrardev99 Yes would be great if you can make a repo!

**Comment by Lucsnchz** [comment]
I have the same problem 😣 i update the package to 1.3.6 and persist the problem

**Comment by Lucsnchz** [comment]
```
                                SelectTree::make('categories')
                                ->label(__('Category'))
                                ->dehydrated(false)
                                ->relationship('categories', 'name', 'parent_id'),
```


The solution was to enter the element: 
->dehydrated(false)
 good luck! :D

**Comment by abrardev99** [comment]
@Lucsnchz That worked. Great thanks.

**Comment by CodeWithDennis** [comment]
This doesnt solve the real problem, could anyone make a repo for it?

**Comment by cxcsz** [comment]
@CodeWithDennis My English is not very good, these are all machine translations, I hope you can understand them.
I also encountered this problem. After checking the code in the film select and your selecttree, I noticed that in line 1069 of vendor\form\forms\src\components\Select.php, there is a code like ` $this ->dehydrated (fn (Select $component): boolean=>$ component->isMultiple());`  To prevent data from entering the main model, I tried adding `$this->dehydrated(fn (SelectTree $component): bool => ! $component->getMultiple());` before the relationship return in vendor\codewithdenis\context-select-tree\src\SelectTree. php  Completed the same function.
Please check if this issue has been resolved and there have been no other impacts. If there is any progress, please @ me. Thank you very much.
