### ISSUE TITLE
[Bug]: Unknown column 'categories' in 'field list'

### ISSUE THREAD

**Issue by ajay-ag** [CodeWithDennis/filament-select-tree#63]
### What happened?

Trying to save category in main table 

### How to reproduce the bug

https://github.com/ajay-ag/select-tree.git

### Package Version

^3.1

### PHP Version

8.2

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by CodeWithDennis** [comment]
Im not 100% sure why its happening but for now you can use `->dehydrated(false)`.

**Comment by CodeWithDennis** [comment]
This should be resolved in the latest release.
