### ISSUE TITLE
[Bug]: Default value is not showing as selected

### ISSUE THREAD

**Issue by iRaziul** [CodeWithDennis/filament-select-tree#65]
### What happened?

I am facing a strange issue while using SelectTree component.
It is working fine on my local machine (Windows 11) but while pushing the code to production the default selected value is not showing.

✅ This is on localhost working as expected:
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/51883557/a0a532c2-976d-4bba-a88d-5ec947194915)

🚫 This is on the production the parent category is not showing:
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/51883557/78ef11b5-f7f1-4557-8fa9-d3b3d2bac938)

I've seen browser's console for any errors but there wasn't any, all the css/js are loading fine.

Here is the code:
```php
SelectTree::make('parent_id')
    ->label('Parent Category')
    ->relationship('parent', 'name', 'parent_id')
    ->defaultOpenLevel(5)
    ->enableBranchNode(),
```

### How to reproduce the bug

I don't know, The code is working fine on localhost but not in production 😔

### Package Version

3.1

### PHP Version

8.2

### Laravel Version

10.41

### Which operating systems does with happen with?

Linux

**Comment by iRaziul** [comment]
Same thing for other resources as well like in `Product`.

```php
SelectTree::make('category_id')
    ->label('Category')
    ->relationship('category', 'name', 'parent_id')
    ->required()
    ->defaultOpenLevel(5)
    ->clearable(false)
    ->placeholder('Select category'),
```

**Comment by iRaziul** [comment]
Here are inspected DOM:

✅ Working:
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/51883557/27f0bfec-efff-4ee6-8e2f-f55f2f0130a5)

🚫 Not Working:
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/51883557/ca2d716c-9804-43fb-b76a-f77ceaae4e20)

**Comment by CodeWithDennis** [comment]
Interesting, have you tried using `->default()`?

**Comment by iRaziul** [comment]
> Interesting, have you tried using `->default()`?

Yes, it selects for the create operation but while edit it doesn't.

**Comment by CodeWithDennis** [comment]
That happens because when you're editing something, the value is already "set" at that point. I think that's how all the fields work in Filament.

**Comment by iRaziul** [comment]
> That happens because when you're editing something, the value is already "set" at that point. I think that's how all the fields work in Filament.

Yeah, but the value should be selected. Actually it is on local

**Comment by CodeWithDennis** [comment]
So what you are saying is when you create a new record with a category, when editing that new record the category is not set?

**Comment by iRaziul** [comment]
> So what you are saying is when you create a new record with a category, when editing that new record the category is not set?

it is set on db but not selected on the SelectTree

**Comment by iRaziul** [comment]
Like this:
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/51883557/a0a532c2-976d-4bba-a88d-5ec947194915)
this is what we expect.

**Comment by iRaziul** [comment]
The creepy part is that it works on localhost 😅

**Comment by iRaziul** [comment]
This is what I get on production 😔
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/51883557/78ef11b5-f7f1-4557-8fa9-d3b3d2bac938)

**Comment by CodeWithDennis** [comment]
You might want to consider reinstalling the package or checking for any potential caching issues. I've demonstrated the process in the video below, and as you can see, it works flawlessly.

https://github.com/CodeWithDennis/filament-select-tree/assets/23448484/6792c0df-e549-48c5-aa3f-f3d733cf50c4

**Comment by iRaziul** [comment]
> You might want to consider reinstalling the package or checking for any potential caching issues. I've demonstrated the process in the video below, and as you can see, it works flawlessly.
> 
>  Schermopname.2024-01-17.om.10.33.39.mov

this is in live server?

**Comment by CodeWithDennis** [comment]
> > You might want to consider reinstalling the package or checking for any potential caching issues. I've demonstrated the process in the video below, and as you can see, it works flawlessly.
> > Schermopname.2024-01-17.om.10.33.39.mov
> 
> this is in live server?

Local, but i got it also working on a live app.

**Comment by iRaziul** [comment]
> > > You might want to consider reinstalling the package or checking for any potential caching issues. I've demonstrated the process in the video below, and as you can see, it works flawlessly.
> > > Schermopname.2024-01-17.om.10.33.39.mov
> > 
> > 
> > this is in live server?
> 
> Local, but i got it also working on a live app.

For me it is working fine on local.

**Comment by CodeWithDennis** [comment]
Not sure how to dig deeper into this. Everything seems to work fine when I follow your examples. Maybe try turning off your AdBlocker; it seems there've been some issues with it lately combined with scripts.

**Comment by iRaziul** [comment]
I have deleted the cache and deployed it a couple of times.

Now the only thing left is to try a different server.
I am going to give it a try.

**Comment by iRaziul** [comment]
> Not sure how to dig deeper into this. Everything seems to work fine when I follow your examples. Maybe try turning off your AdBlocker; it seems there've been some issues with it lately combined with scripts.

AdBlockr is not issue as I've tested on mobile phone as well.

Let me try a fresh code and post update here.

**Comment by iRaziul** [comment]
There is no issue with this package.

I have deployed the same project on another server and everything works as expected.
