### ISSUE TITLE
[Bug]: SelectTree flickering issue

### ISSUE THREAD

**Issue by zlatangoralija** [CodeWithDennis/filament-select-tree#68]
### What happened?

When putting `live()` method on the `SelectTree` form component, and selecting one of the optioons, it starts flickering unexpectedly, and I can't change my selection. 

### How to reproduce the bug

Crate a SelectTree component like this:

```
SelectTree::make('groups')
   ->relationship('groups', 'name', 'parent_id')
   ->hiddenOn('edit')
   ->enableBranchNode()
   ->live(),
```

For the groups relation, i'm using[ lazychaser/laravel-nestedset](https://github.com/lazychaser/laravel-nestedset). Data looks like this: 

![image](https://github.com/CodeWithDennis/filament-select-tree/assets/36918435/4b973000-a5d1-43ea-b385-4e0e585af446)

Now, when I select one of the groups, it just starts flickering: 

https://github.com/CodeWithDennis/filament-select-tree/assets/36918435/217d01c2-1beb-4e76-a9ff-32432f30c57d

After that, I can't change the selected option. I have to refresh the page in order for the component to work again. 
                    

### Package Version

3.1.21

### PHP Version

8.2.14

### Laravel Version

10.35.0

### Which operating systems does with happen with?

macOS

### Notes

I see that there was a fix for this in #66 but it was later reverted in #67. What was reason for that? Was that fix breaking something else?

**Comment by CodeWithDennis** [comment]
Thanks for reporting this issue, it seems like all the issues are connected to the `wire:key` part, i will try to take a look this weekend hopefully i can get it all sorted out at once.

Yes #66 was fixing it but made the field not reactive/live anymore.

**Comment by zlatangoralija** [comment]
Thanks for looking into this.

**Comment by CodeWithDennis** [comment]
@zlatangoralija Can you tell me if this is fixed since the latest release?
