### ISSUE TITLE
[Bug]: Should remove an editable category from the list

### ISSUE THREAD

**Issue by projct1** [CodeWithDennis/filament-select-tree#76]
### What happened?

A category cannot be its own parent.
If I select the current edited category as its parent, then I get an unpredictable binding:
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/9752959/64fa53db-808c-47ab-87f4-817a61068d93)

And real parent not display (need an extra click):
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/9752959/07a1edb2-49be-43b3-97e9-b87265cecb5f)

### How to reproduce the bug

```php
public static function form(Form $form): Form
{
    return $form
        ->schema([
            TextInput::make('name')->maxLength(255)->required(),
            TextInput::make('slug')->maxLength(255)->required(),
            TextInput::make('position')->numeric(),
            SelectTree::make('parent_id')
                ->withCount()
                ->enableBranchNode()
                ->relationship('parent', 'name', 'parent_id')
        ]);
}
```

### Package Version

3.1.25

### PHP Version

8.3

### Laravel Version

10.43

**Comment by CodeWithDennis** [comment]
This is not something the field should enforce, if you want to disable certain options you can with `->disabledOptions()`
