### ISSUE TITLE
[feature]: Need option for expand all nodes on load

### ISSUE THREAD

**Issue by projct1** [CodeWithDennis/filament-select-tree#77]
### What happened?

![image](https://github.com/CodeWithDennis/filament-select-tree/assets/9752959/e1ee18d1-c961-4727-a838-5b00ded8e5ba)

With large trees it will be tedious to open everything manually :(

### How to reproduce the bug

```php
public static function form(Form $form): Form
{
    return $form
        ->schema([
            TextInput::make('name')->maxLength(255)->required(),
            TextInput::make('slug')->maxLength(255)->required(),
            TextInput::make('position')->numeric(),
            SelectTree::make('parent_id')
                ->withCount()
                ->enableBranchNode()
                ->relationship('parent', 'name', 'parent_id')
        ]);
}
```

### Package Version

3.1

### PHP Version

8.3

### Laravel Version

10.43

**Comment by CodeWithDennis** [comment]
Unfortunately this is not possible with the underlying package.
