### ISSUE TITLE
[Help wanted]: Need more description for options

### ISSUE THREAD

**Issue by projct1** [CodeWithDennis/filament-select-tree#78]
### What happened?

What is `independent`, `expandSelected`, `grouped`?
Switching these options I didn't notice any difference :(
Need more examples plz :)

### How to reproduce the bug

```php
public static function form(Form $form): Form
{
    return $form
        ->schema([
            TextInput::make('name')->maxLength(255)->required(),
            TextInput::make('slug')->maxLength(255)->required(),
            TextInput::make('position')->numeric(),
            SelectTree::make('parent_id')
                ->withCount()
                ->enableBranchNode()
                ->relationship('parent', 'name', 'parent_id')
        ]);
}
```

### Package Version

3.1

### PHP Version

8.3

### Laravel Version

10.43

**Comment by CodeWithDennis** [comment]
It seems like there might be a language barrier. Please read the instructions carefully as it does what it says.
