### ISSUE TITLE
[Bug]: Unable to save category_id

### ISSUE THREAD

**Issue by atapatel** [CodeWithDennis/filament-select-tree#79]
### What happened?

I am unable to save category_id. On browser console I get following error.
```
Livewire Entangle Error: Livewire property ['data.category_id'] cannot be found on component: ['app.filament.contractor.resources.project-template-resource.pages.create-project-template']
module_default.interceptor.Object.defineProperty.get.isLive @ livewire.js?id=a27c4ca2:3846
```

### How to reproduce the bug

Adding SelectTree input filed in Resource.

### Package Version

3.1.26

### PHP Version

8.1.0

### Laravel Version

10.0

### Which operating systems does with happen with?

macOS

**Comment by CodeWithDennis** [comment]
Need more information, perhaps a repo.

**Comment by atapatel** [comment]
I have solve this issue by adding below code in Create[ANY_RESOURCE]Record .
```
    protected function afterFill()
    {
        $this->fill(['data' => ['category_id'=>'']]);
    }
 ```
