### ISSUE TITLE
[Bug]: Data not passing

### ISSUE THREAD

**Issue by iRaziul** [CodeWithDennis/filament-select-tree#87]
### What happened?

I found a serious but weird issue. 🫨

My models are `Category` and `Product` where the category has child categories.

I used this code to select a category for the product and this was working fine but for the last couple of days it is not working as expected.
```php
SelectTree::make('category_id')
    ->label('Category')
    ->required()
    ->relationship('category', 'name', 'parent_id')
    ->defaultOpenLevel(5)
    ->placeholder('Select category'),
```
This renders the field as I wanted:
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/51883557/74315588-9931-484e-a14a-2139df3148f4)

I've selected the category and submitted the form but got this response: 
![image](https://github.com/CodeWithDennis/filament-select-tree/assets/51883557/8c5ad79c-8196-4d83-9acd-54e0c3b5eb76)

### How to reproduce the bug

```php
SelectTree::make('category_id')
    ->label('Category')
    ->required()
    ->relationship('category', 'name', 'parent_id')
    ->defaultOpenLevel(5)
    ->placeholder('Select category'),
```

### Package Version

3.1.32

### PHP Version

8.2

### Laravel Version

10.4

### Which operating systems does with happen with?

Windows, Linux

### Notes

I can provide you the website link privately so that you can have a look.

**Comment by CodeWithDennis** [comment]
This might have to do with the same issue (https://github.com/CodeWithDennis/filament-select-tree/pull/85) @saade

@iRaziul Could you check if `dehydrated(true)` fixes it?

**Comment by iRaziul** [comment]
> This might have to do with the same issue (#85) @saade
> 
> @iRaziul Could you check if `dehydrated(true)` fixes it?

Yeah it seems like working after using `dehydrated()`

**Comment by Sjoerd24** [comment]
I have the same problem, data is not on any field passing through. Is the mentioned fixed above a def fix or is a better solution coming along? Bit weird that all selecttree fields aren't working anymore in my site, luckly still in testing fase. :)

edit: ->dehydrated(true) fixes also my problem. But this shouldn't be standard behaviour right?

**Comment by saade** [comment]
#89

**Comment by CodeWithDennis** [comment]
> #89

Merged, please check your application with the latest version. @Sjoerd24

**Comment by Sjoerd24** [comment]
@CodeWithDennis Thanks, it all works now again!
