### ISSUE TITLE
SelectTree Component Does Not Save Parent Area in Database

### ISSUE THREAD

**Issue by zeyadsharo** [CodeWithDennis/filament-select-tree#93]
### What happened?

SelectTree component, when used in the AreaResource, does not save the selected parent area into the database. There are no error messages displayed, making it difficult to diagnose the issue.

Component/Area:
```php
 public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TextInput::make('arabic_title')->required(),
                TextInput::make('kurdish_title')->required(),
              
                SelectTree::make('parentArea')
                     ->relationship('parentArea', 'arabic_title', 'parent_id')
                     ->placeholder(__('Please select a Area'))
                ->withCount()
                ->direction('buttom')
                     ->label(__('Parent Area'))->nullable(),
                TextInput::make('latitude')
                    ->required()
                    ->rules('numeric'),
                TextInput::make('longitude')
                    ->required()
                    ->rules('numeric'),
            ]);
    }

```

Model:

```php
class Area extends Model
{
    use HasFactory;
    protected $fillable = [
        'arabic_title', 'kurdish_title', 'parent_id', 'latitude', 'longitude'
    ];

    public function parentArea()
    {
        return $this->belongsTo(Area::class, 'parent_id');
    }
}
```
migration:
```php
Schema::create('areas', function (Blueprint $table) {
            $table->id();
            $table->string('arabic_title');
            $table->string('kurdish_title');
            $table->unsignedBigInteger('parent_id')->nullable();
            $table->foreign('parent_id')->references('id')->on('areas')->onDelete('cascade');
            $table->decimal('latitude', 13, 9);
            $table->decimal('longitude', 13, 9);
            $table->timestamps();
        });


```

![image](https://github.com/CodeWithDennis/filament-select-tree/assets/33178745/d3acce4c-2b5a-4b10-8034-c2ebd23ef970)

### How to reproduce the bug

Steps to Reproduce:

1. Go to the AreaResource form in the application.
2. Use the SelectTree to choose a parent area.
3. Save the form.
4. Check the database or refresh the form; the parent area is not updated in the database.

Expected Result:
The selected parent area should be saved into the database and be visible when retrieving or refreshing the Area details.

Actual Result:
The parent area selection is not saved into the database, and no errors are displayed, indicating a silent failure.

### Package Version

3.1

### PHP Version

8.1

### Laravel Version

10.10

### Which operating systems does with happen with?

Windows

**Comment by CodeWithDennis** [comment]
Since `parentArea` is a BelongsTo im assuming it saves a single ID to this column? Try adding `parentArea` to your fillable.
