### ISSUE TITLE
[Bug]: Trait "Filament\Forms\Components\Concerns\HasPivotData" not found

### ISSUE THREAD

**Issue by matinrajabi** [CodeWithDennis/filament-select-tree#94]
### What happened?

i get this error in my create form page.

### How to reproduce the bug

it work properly in my local project i pushed it into git repo and pull in another system. in another system got this error

### Package Version

3.1

### PHP Version

8.0.2

### Laravel Version

10.10

**Comment by CodeWithDennis** [comment]
Try updating Filament to the latest version.

**Comment by codeies** [comment]
@CodeWithDennis its same issue with latest Filament
